---
- name: Add an Apt signing key
  ansible.builtin.apt_key:
    id: "{{ item.id | default(omit) }}"
    url: "{{ item.url }}"
    keyring: "{{ item.keyring | default(omit) }}"
    state: present
  with_items:
    - "{{ apt_keys }}"
