---
- import_tasks: check.yml
  tags: check

- import_tasks: dependecies.yml
  tags: dependencies

- import_tasks: keys.yml
  when: apt_keys | length > 0
  tags: keys

- import_tasks: repositories.yml
  when: apt_repositories | length > 0
  tags: repositiores

- import_tasks: packages.yml
  when: apt_packages | length > 0
  tags: packages
