---
- import_tasks: check.yml
  tags: check

- import_tasks: dependecies.yml
  tags: dependencies

- import_tasks: keys.yml
  when: apt_keys | length > 0
  tags: keys

- import_tasks: sources.yml
  when: apt_sources | length > 0
  tags: sources

- import_tasks: repositories.yml
  when: apt_repositories | length > 0
  tags: repositories

- import_tasks: repositories_unmanaged.yml
  when: apt_repositories_remove_unmanaged
  tags: repositories

- import_tasks: preferences.yml
  when: apt_preferences | length > 0
  tags: preferences

- import_tasks: packages.yml
  when: apt_packages | length > 0
  tags: packages
