---
- name: Install apt packages
  ansible.builtin.apt:
    allow_unauthenticated: "{{ item.allow_unauthenticated | default(omit) }}"
    autoclean: "{{ item.autoclean | default(omit) }}"
    autoremove: "{{ item.autoremove | default(omit) }}"
    cache_valid_time : "{{ item.cache_valid_time | default(3600) }}"
    deb: "{{ item.deb | default(omit) }}"
    default_release: "{{ item.default_release | default(omit) }}"
    dpkg_options: "{{ item.dpkg_options | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    force_apt_get: "{{ item.force_apt_get | default(yes) }}"
    install_recommends: "{{ item.install_recommends | default(omit) }}"
    name: "{{ item.name }}"
    only_upgrade: "{{ item.only_upgrade | default(omit) }}"
    policy_rc_d: "{{ item.policy_rc_d | default(omit) }}"
    purge: "{{ item.purge | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    update_cache: "{{ item.update_cache | default(yes) }}"
    update_cache_retries: "{{ item.update_cache_retries | default(omit)}}"
    update_cache_retry_max_delay: "{{ item.update_cache_retry_max_delay | default(omit) }}"
    upgrade: "{{ item.upgrade | default(omit) }}"
  with_items:
    - "{{ apt_packages }}"
