---
- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "{{ apt_packages }}"