---
- name: Add apt preferences
  ansible.builtin.template:
    src: preferences.j2
    dest: "/etc/apt/preferences.d/{{ item.filename }}.pref"
    owner: root
    group: root
    mode: 0644
  when: item.state | default("present") == "present"
  register: template_preferences
  with_items:
    - "{{ apt_preferences }}"

- name: Remove apt preferences
  ansible.builtin.file:
    dest: "/etc/apt/preferences.d/{{ item.filename }}.pref"
    state: absent
  when: item.state | default("present") == "absent"
  register: remove_preferences
  with_items:
    - "{{ apt_preferences }}"

# it's no in handlers, because flush_handlers task does not support when conditional
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: yes
  when: template_preferences is changed or remove_preferences is changed
