---
- name: Add apt preferences
  ansible.builtin.template:
    src: preferences.j2
    dest: "{{ apt_preferences_path + item.filename + apt_preferences_ext }}"
    owner: root
    group: root
    mode: 0644
  when: item.state | default("present") == "present"
  register: apt_template_preferences
  with_items:
    - "{{ apt_preferences }}"

- name: Remove apt preferences
  ansible.builtin.file:
    dest: "{{ apt_preferences_path + item.filename + apt_preferences_ext }}"
    state: absent
  when: item.state | default("present") == "absent"
  register: apt_remove_preferences
  with_items:
    - "{{ apt_preferences }}"

# it's no in handlers, because flush_handlers task does not support when conditional
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: yes
  when: apt_template_preferences is changed or apt_remove_preferences is changed
