---
- name: Add repositories into sources list
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.name | default(omit) }}"
  with_items:
    - "{{ apt.repositories }}"
