---
- name: Template source.list
  ansible.builtin.template:
    src: source.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  register: apt_template_source_list

# it's no in handlers, because flush_handlers task does not support when conditional
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: yes
  when: apt_template_source_list is changed
