---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: debian9
    image: moletti/molecule-debian:9
    pre_build_image: true
    privileged: true
    groups: ["debian"]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian10
    image: moletti/molecule-debian:10
    pre_build_image: true
    privileged: true
    groups: ["debian"]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu18
    image: moletti/molecule-ubuntu:18.04
    pre_build_image: true
    privileged: true
    groups: ["ubuntu"]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu20
    image: moletti/molecule-ubuntu:20.04
    pre_build_image: true
    privileged: true
    groups: ["ubuntu"]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  inventory:
    group_vars:
      ubuntu:
        apt_sources:
          - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
          - "deb http://ftp.us.debian.org/debian/ {{ansible_distribution_release}} main"
          - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"
      debian:
        apt_sources:
          - "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main"
          - "deb http://security.debian.org/debian-security {{ ansible_distribution_release }}/updates main"

verifier:
  name: ansible
