---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .

platforms:
  - name: debian9
    image: moletti/molecule-debian:9
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian10
    image: moletti/molecule-debian:10
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
