---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - "../include_vars/apt.yml"
  tasks:
    - name: Gathering package_facts
      ansible.builtin.package_facts:
        manager: apt
