---
- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - "../include_vars/apt.yml"
  tasks:
    - name: Gathering package_facts
      ansible.builtin.package_facts:
        manager: apt
    - name: Test packages
      assert:
        that:
          - "{% if item.state in ('present', 'latest') -%}
              {%- if item.name is subset ansible_facts.packages.keys() -%}
                True
              {%- else -%}
                False
              {%- endif -%}
             {%- endif -%}"
          - "{% if item.state in ('absent') -%}
              {%- if item.name is not subset ansible_facts.packages.keys() -%}
                True
              {%- else -%}
                False
              {%- endif -%}
             {%- endif -%}"
        quiet: true
      with_items:
        - "{{ apt_packages }}"
