apt_packages:
  - name: ['htop', 'nload', 'vim']
    state: present
  - name: ['less']
    state: latest
  - name: ['nano']
    state: absent
apt_keys:
  - url: https://nginx.org/keys/nginx_signing.key
apt_repositories:
  - filename: nginx
    repo: "deb https://nginx.org/packages/mainline/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
apt_preferences:
  - package: 'some_package'
    filename: 'some'
    pin: 'release a=testing'
    priority: 800
  - package: '*'
    state: absent
    filename: 'unused'
    pin: 'release a=testing'
    priority: 0
