apt_packages:
  - name: ['htop', 'nload', 'vim']
  - name: ['less']
    state: latest
apt_keys:
  - url: https://nginx.org/keys/nginx_signing.key
apt_repositories:
  - repo: "deb https://nginx.org/packages/mainline/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
